services:
  mysql:
    image: mariadb:11.4
    container_name: mythicaldash_v3_mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-mythicaldash_v3_root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-mythicaldash_v3}
      MARIADB_USER: ${MARIADB_USER:-mythicaldash_v3}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-mythicaldash_v3_password}
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mythicaldash_v3_network
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pmythicaldsah_v3_root",
        ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: mythicaldash_v3_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-mythicaldash_v3_redis}
    volumes:
      - redis_data:/data
    networks:
      - mythicaldash_v3_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  backend:
    image: ghcr.io/mythicalltd/mythicaldash_v3-backend:dev
    container_name: mythicaldash_v3_backend
    restart: unless-stopped
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_DATABASE=${MARIADB_DATABASE:-mythicaldash_v3}
      - DATABASE_USER=${MARIADB_USER:-mythicaldash_v3}
      - DATABASE_PASSWORD=${MARIADB_PASSWORD:-mythicaldash_v3_password}
      - DATABASE_ENCRYPTION=xchacha20
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD:-mythicaldash_v3_redis}
      - DATABASE_ENCRYPTION_KEY=${DATABASE_ENCRYPTION_KEY:-zKZ7//AocUD2wCuzjW5rdTbb8FvGBgKTZ8iCATslZ/8=}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "cli", "help"]
      timeout: 20s
      retries: 10
    volumes:
      - mythicaldash_v3_attachments:/var/www/html/public/attachments
      - ./.env:/var/www/html/storage/.env
      - mythicaldash_v3_snapshots:/var/www/html/storage/backups
    networks:
      - mythicaldash_v3_network

  frontend:
    image: ghcr.io/mythicalltd/mythicaldash_v3-frontend:dev
    container_name: mythicaldash_v3_frontend
    restart: unless-stopped
    volumes: []
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      timeout: 20s
      retries: 10
    ports:
      - "4832:80"
    networks:
      - mythicaldash_v3_network

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  mythicaldash_v3_attachments:
    driver: local
  mythicaldash_v3_snapshots:
    driver: local

networks:
  mythicaldash_v3_network:
    driver: bridge
