CREATE TABLE
	`mythicaldash_servers_queue` (
		`id` INT NOT NULL AUTO_INCREMENT,
		`name` TEXT NOT NULL,
		`description` TEXT NOT NULL,
		`status` ENUM('pending', 'building', 'failed') NOT NULL DEFAULT 'pending',
		`ram` INT NOT NULL,
		`disk` INT NOT NULL,
		`cpu` INT NOT NULL,
		`ports` INT NOT NULL,
		`databases` INT NOT NULL,
		`backups` INT NOT NULL,
		`location` INT NOT NULL,
		`user` varchar(36) NOT NULL,
		`nest` INT NOT NULL,
		`egg` INT NOT NULL,
		`deleted` ENUM ('false', 'true') NOT NULL DEFAULT 'false',
		`locked` ENUM ('false', 'true') NOT NULL DEFAULT 'false',
		`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		PRIMARY KEY (`id`),
		FOREIGN KEY (`location`) REFERENCES `mythicaldash_locations` (`id`),
        FOREIGN KEY (`user`) REFERENCES `mythicaldash_users` (`uuid`),
		FOREIGN KEY (`nest`) REFERENCES `mythicaldash_eggs_categories` (`id`),
		FOREIGN KEY (`egg`) REFERENCES `mythicaldash_eggs` (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci;