<!-- Core JS -->
<script src="<?= $appURL ?>/assets/vendor/libs/jquery/jquery.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/popper/popper.js"></script>
<script src="<?= $appURL ?>/assets/vendor/js/bootstrap.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/node-waves/node-waves.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/hammer/hammer.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/i18n/i18n.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/typeahead-js/typeahead.js"></script>
<script src="<?= $appURL ?>/assets/vendor/js/menu.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/moment/moment.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/select2/select2.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/apex-charts/apexcharts.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/formvalidation/dist/js/FormValidation.min.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/formvalidation/dist/js/plugins/Bootstrap5.min.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/formvalidation/dist/js/plugins/AutoFocus.min.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/cleavejs/cleave.js"></script>
<script src="<?= $appURL ?>/assets/vendor/libs/cleavejs/cleave-phone.js"></script>
<!--<script src="<?= $appURL ?>/assets/js/MythicalGuard.js"></script>-->

<!-- Main JS -->
<script src="<?= $appURL ?>/assets/js/main.js"></script>