INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BUNGEE_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SERVER_JARFILE', 'server.jar');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BUILD_NUMBER', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MC_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BUILD_TYPE', 'recommended');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('VANILLA_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('NUKKIT_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('VERSION', 'pm4');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MINECRAFT_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BEDROCK_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('LD_LIBRARY_PATH', '.');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('GAMEMODE', 'survival');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('CHEATS', 'false');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('DIFFICULTY', 'easy');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SERVERNAME', 'My Bedrock Server');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('PMMP_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('USER_UPLOAD', '0');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('AUTO_UPDATE', '0');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BOT_JS_FILE', 'index.js');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BOT_PY_FILE', 'index.py');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('TS_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('FILE_TRANSFER', '30033');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MAX_USERS', '100');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MUMBLE_VERSION', 'latest');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('REQUIREMENTS_FILE', 'requirements.txt');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('PY_FILE', 'app.py');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('GO_PACKAGE', 'changeme');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('EXECUTABLE', 'changeme');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('LUA_FILE', 'app.lua');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('LIT_PACKAGES', '');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('JS_FILE', 'index.js');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('JARFILE', 'app.jar');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MAIN_FILE', 'index.js');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('PROJECT_FILE', 'MyProject.sln');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('PROJECT_DIR', '/home/container');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('PGUSER', 'pterodactyl');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('PGPASSWORD', 'Pl3453Ch4n63M3!');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SERVER_PASSWORD', 'P@55w0rd');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MONGO_USER', 'admin');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MONGO_USER_PASS', '');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('DRIVER_PORT', '25568');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('HTTP_PORT', '25569');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('FIVEM_LICENSE', '');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('MAX_PLAYERS', '48');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SERVER_HOSTNAME', 'My new FXServer');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('FIVEM_VERSION', 'recommended');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('STEAM_WEBAPIKEY', 'none');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('TXADMIN_PORT', '40120');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('TXADMIN_ENABLE', '0');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SERVER_NAME', 'RAGE:MP Unofficial server');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('Version', 'R2-1');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('RCON_PASS', 'RCON_PASS');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('HOSTNAME', 'A Rust Server');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('OXIDE', '0');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('LEVEL', 'Procedural Map');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('DESCRIPTION', 'Powered by Pterodactyl');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('WORLD_SIZE', '3000');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('RCON_PORT', '28016');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SAVEINTERVAL', '60');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('APP_PORT', '28082');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('QUERY_PORT', '10011');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('QUERY_PROTOCOLS_VAR', 'raw,http,ssh');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('QUERY_SSH', '10022');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('QUERY_HTTP', '10080');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SRCDS_APPID', '232250');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SRCDS_MAP', 'cp_dustbowl');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('STEAM_ACC', 'kFXByFpKBNyNScAZNTmbfJhMDUXVdZrX');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('TICKRATE', '22');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('LUA_REFRESH', '0');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('ARK_ADMIN_PASSWORD', 'PleaseChangeMe');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SERVER_MAP', 'TheIsland');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('SESSION_NAME', 'A Pterodactyl Hosted ARK Server');
INSERT INTO `mythicaldash_eggs_config` (`setting_name`, `setting_value`) VALUES ('BATTLE_EYE', '1');
