ALTER TABLE `mythicaldash_settings`
  DROP `FEEDBACK_1_NAME`,
  DROP `FEEDBACK_1_ROLE`,
  DROP `FEEDBACK_1_AVATAR`,
  DROP `FEEDBACK_1_DESCRIPTION`,
  DROP `FEEDBACK_2_NAME`,
  DROP `FEEDBACK_2_ROLE`,
  DROP `FEEDBACK_2_AVATAR`,
  DROP `FEEDBACK_2_DESCRIPTION`,
  DROP `FEEDBACK_3_NAME`,
  DROP `FEEDBACK_3_ROLE`,
  DROP `FEEDBACK_3_AVATAR`,
  DROP `FEEDBACK_3_DESCRIPTION`;